import type { PipelineSpec } from "@/lib/spec"

/**
 * Render a config value in confection (config.cfg) syntax: JSON values,
 * with the same conventions `spacy init config` output uses.
 */
export function cfgValue(value: unknown): string {
  if (value === null || value === undefined) return "null"
  if (typeof value === "string") return JSON.stringify(value)
  if (typeof value === "boolean" || typeof value === "number") return String(value)
  return JSON.stringify(value)
}

/**
 * Generate a minimal config.cfg. Only override keys are written; spaCy's
 * config system auto-fills factory defaults on load.
 */
export function generateConfig(spec: PipelineSpec): string {
  const lines: string[] = []
  lines.push("# Generated by the spaCy Pipeline Composer.")
  lines.push("# Build with: python -m spacy assemble config.cfg ./output")
  lines.push("# Trainable components need training before they produce output.")
  if (spec.base.type === "model") {
    lines.push(`# NOTE: this pipeline was composed on top of trained model "${spec.base.name}".`)
    lines.push("# Only the added components are listed; use the Python export for the full setup.")
  }
  lines.push("")
  lines.push("[nlp]")
  lines.push(`lang = ${cfgValue(spec.lang)}`)
  lines.push(`pipeline = ${JSON.stringify(spec.components.map((c) => c.name))}`)
  lines.push("")
  if (spec.components.length) {
    lines.push("[components]")
    lines.push("")
  }

  for (const comp of spec.components) {
    lines.push(`[components.${comp.name}]`)
    lines.push(`factory = ${cfgValue(comp.factory)}`)
    for (const [key, value] of Object.entries(comp.config)) {
      if (value !== null && typeof value === "object" && !Array.isArray(value)) {
        continue // nested dicts would need subsections; none of our fields emit them
      }
      lines.push(`${key} = ${cfgValue(value)}`)
    }
    if (comp.patterns?.length) {
      lines.push(`# ${comp.patterns.length} ruler pattern(s) are not expressible in config.cfg;`)
      lines.push("# add them at runtime via pipe.add_patterns(...) or an initialize callback.")
    }
    lines.push("")
  }
  return lines.join("\n")
}
