import coreWebVitals from 'eslint-config-next/core-web-vitals'

// Flat config (ESLint 9). Replaces .eslintrc.json, which extended
// "next/core-web-vitals" (`next lint` was removed in Next 16).
// The eslint-config-next flat export already ignores .next/, out/,
// build/ and next-env.d.ts.
export default [
    ...coreWebVitals,
    {
        ignores: [
            'public/**',
            'setup/**',
            'docs/**',
            // generated by setup/setup.sh at build time
            'meta/site.generated.mjs',
        ],
    },
    {
        // Parity with the previous `next lint` baseline (ESLint 8 +
        // eslint-config-next 15): these rules are newly enforced by
        // eslint-config-next 16 / eslint-plugin-react-hooks 7 and produced
        // findings in long-standing code. Tuned off rather than mass-fixing
        // unrelated code in the upgrade branch (see MIGRATION_LOG.md).
        rules: {
            'react/no-unescaped-entities': 'off',
            'react-hooks/set-state-in-effect': 'off',
            'react-hooks/immutability': 'off',
            'react-hooks/refs': 'off',
            'import/no-anonymous-default-export': 'off',
        },
    },
]
